# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_args_BinanceMarketStream__depth <- function(symbol, speed, handler) {
  assert_scalar_character(symbol)
  assert_scalar_character(speed)
  assert_value_in_set(speed, c("1000ms", "100ms"))
  if (!is.null(handler)) {
    assert_function(handler)
  }
  return(invisible(NULL))
}

assert_return_BinanceMarketStream__depth <- function(value) {
  assert_class(value, "BinanceMarketStream")
  return(value)
}

assert_args_BinanceWsBase__initialize <- function(base_url, auto_reconnect, max_reconnects, proactive_reconnect) {
  assert_scalar_character(base_url)
  assert_scalar_logical(auto_reconnect)
  assert_scalar_count(max_reconnects)
  assert_between(max_reconnects, lower = 1)
  assert_scalar_logical(proactive_reconnect)
  return(invisible(NULL))
}

assert_return_BinanceWsBase__initialize <- function(value) {
  assert_class(value, "BinanceWsBase")
  return(value)
}

assert_args_BinanceWsBase__on <- function(event, handler) {
  assert_scalar_character(event)
  assert_value_in_set(event, c("open", "message", "close", "error"))
  assert_function(handler)
  return(invisible(NULL))
}

assert_return_BinanceWsBase__on <- function(value) {
  assert_class(value, "BinanceWsBase")
  return(value)
}

assert_return_BinanceWsBase__connect <- function(value) {
  assert_class(value, "BinanceWsBase")
  return(value)
}

assert_args_BinanceWsBase__subscribe <- function(streams) {
  assert_character(streams)
  assert_no_missing_values(streams)
  return(invisible(NULL))
}

assert_return_BinanceWsBase__subscribe <- function(value) {
  assert_class(value, "BinanceWsBase")
  return(value)
}

assert_args_BinanceWsBase__unsubscribe <- function(streams) {
  assert_character(streams)
  assert_no_missing_values(streams)
  return(invisible(NULL))
}

assert_return_BinanceWsBase__unsubscribe <- function(value) {
  assert_class(value, "BinanceWsBase")
  return(value)
}

assert_args_BinanceWsBase__send <- function(message) {
  assert_scalar_character(message)
  return(invisible(NULL))
}

assert_return_BinanceWsBase__send <- function(value) {
  assert_class(value, "BinanceWsBase")
  return(value)
}

assert_args_BinanceWsBase__run <- function(timeout) {
  assert_scalar_double(timeout)
  assert_between(timeout, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_BinanceWsBase__run <- function(value) {
  assert_class(value, "BinanceWsBase")
  return(value)
}

assert_return_BinanceWsBase__close <- function(value) {
  assert_class(value, "BinanceWsBase")
  return(value)
}

assert_return_BinanceWsBase__subscriptions <- function(value) {
  assert_character(value)
  assert_no_missing_values(value)
  return(value)
}

assert_return_BinanceWsBase__is_open <- function(value) {
  assert_scalar_logical(value)
  return(value)
}

assert_args_ws_control_message <- function(method, params, id) {
  assert_scalar_character(method)
  assert_value_in_set(method, c("SUBSCRIBE", "UNSUBSCRIBE", "LIST_SUBSCRIPTIONS"))
  assert_character(params)
  assert_no_missing_values(params)
  assert_scalar_count(id)
  assert_between(id, lower = 1)
  return(invisible(NULL))
}

assert_return_ws_control_message <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_ws_depth_stream <- function(symbol, speed) {
  assert_scalar_character(symbol)
  assert_scalar_character(speed)
  assert_value_in_set(speed, c("1000ms", "100ms"))
  return(invisible(NULL))
}

assert_return_ws_depth_stream <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_ws_backoff_delay <- function(attempt, cap_seconds) {
  assert_scalar_count(attempt)
  assert_between(attempt, lower = 1)
  assert_scalar_double(cap_seconds)
  assert_between(cap_seconds, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_ws_backoff_delay <- function(value) {
  assert_scalar_double(value)
  assert_between(value, lower = 1, upper = Inf, upper_inclusive = FALSE)
  return(value)
}

